name: 'Semrel'
description: 'GitHub Action to detect new versions and generate release notes using semrel'
author: 'Brian Bruggeman'
inputs:
  branch:
    description: 'Branch to check out'
    required: false
    default: 'main'
  path:
    description: 'Path to project files'
    required: false
    default: '.'
outputs:
  current-version:
    description: 'The current version'
  log:
    description: 'Base64 encoded commit log for the next version'
  next-version:
    description: 'The next version'
  release-notes:
    description: 'Base64 encoded release notes for the next version'
  version-changed:
    description: 'Identifies if current and next versions are different'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0

    - name: Install jq
      shell:  bash
      run: sudo apt-get install -y jq

    - name: Get latest semrel release
      id: get-latest-release
      shell:  bash
      run: |
        release_data=$(curl --silent "https://api.github.com/repos/brianbruggeman/semrel/releases/latest")
        tag_name=$(echo "$release_data" | jq -r .tag_name)
        assets=$(echo "$release_data" | jq -r '.assets[]')
        asset_tag=$(echo "semrel-${tag_name}-x86_64-unknown-linux-musl.tgz")
        good_assets=$(echo "$assets" | jq -r 'select(.name == "${asset_tag}")')
        found_asset_id=$(echo "$good_assets" | jq -r '.id')
        asset_id=$(echo "$release_data" | jq -r --arg asset_tag "$asset_tag" '.assets[] | select(.name == $asset_tag) | .id')
        asset_url=$(echo "https://api.github.com/repos/brianbruggeman/semrel/releases/assets/$asset_id")
        semrel_filename=$(echo "semrel-$tag_name-x86_64-unknown-linux-musl")

        echo "release_data=${release_data}"
        echo "assets=${assets}"
        echo "tag_name=${tag_name}"
        echo "asset_tag=${asset_tag}"
        echo "good_assets=${good_assets}"
        echo "found_asset_id=${found_asset_id}"
        echo "asset_id=${asset_id}"
        echo "asset_url=${asset_url}"
        echo "semrel_filename=${semrel_filename}"

        echo "tag_name=$tag_name" >> $GITHUB_ENV
        echo "asset_url=$asset_url" >> $GITHUB_ENV
        echo "semrel_filename=$semrel_filename" >> $GITHUB_ENV

    - name: Download and extract semrel
      shell: bash
      run: |
        curl -L -H "Accept: application/octet-stream" -o ${{ env.semrel_filename }}.tgz ${{ env.asset_url }}
        tar -xzf ${{ env.semrel_filename }}.tgz -C . --strip-components=1
        chmod +x ${{ env.semrel_filename }}
        mv ${{ env.semrel_filename }} ./semrel

    - name: Set outputs
      id: semrel
      shell:  bash
      run: |
        current_version=$(./semrel --path=${{ inputs.path }} show current)
        log=$(./semrel --path=${{ inputs.path }} show log)
        next_version=$(./semrel --path=${{ inputs.path }} show next)
        release_notes=$(./semrel --path=${{ inputs.path }} show notes)

        # Encode multiline outputs to base64 to handle special characters and newlines
        encoded_release_notes=$(echo "$release_notes" | base64 | tr -d '\n')
        encoded_log=$(echo "$log" | base64 | tr -d '\n')

        echo "current-version=$current_version" >> $GITHUB_OUTPUT
        echo "next-version=$next_version" >> $GITHUB_OUTPUT
        echo "release-notes=$encoded_release_notes" >> $GITHUB_OUTPUT
        echo "log=$encoded_log" >> $GITHUB_OUTPUT

        if [ "$next_version" != "$current_version" ]; then
          echo "Version is updated."
          echo " - Current version: $current_version"
          echo " - Next version: $next_version"
          printf "%s\n" "$release_notes"
          echo "# Log"
          printf "%s\n" "$log"
          echo "version-changed=true" >> $GITHUB_OUTPUT
        else
          echo "Version is the same."
          echo " - version: $current_version"
          echo "# Log"
          printf "%s\n" "$log"
          echo "version-changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Debug Outputs
      run: |
        echo "version-changed: ${{ steps.semrel.outputs.version-changed }}"
        echo "current-version: ${{ steps.semrel.outputs.current-version }}"
        echo "next-version: ${{ steps.semrel.outputs.next-version }}"
        echo "release-notes: ${{ steps.semrel.outputs.release-notes }}"
        echo "log: ${{ steps.semrel.outputs.log }}"

        # Debug: Print the GITHUB_OUTPUT file to verify it's correct
        echo "DEBUG: Contents of GITHUB_OUTPUT:"
        cat $GITHUB_OUTPUT
