name: Audit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit SHA to run the workflow on'
        required: true
        default: 'main'

permissions:
    checks: write
    issues: write

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: rustsec/audit-check@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
