name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  cargo_fmt:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run semrel
        id: semrel
        uses: brianbruggeman/semrel@main

      - name: Install nightly
        if: ${{ steps.semrel.outputs.next-version != steps.semrel.outputs.current-version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install cargo fmt
        if: ${{ steps.semrel.outputs.next-version != steps.semrel.outputs.current-version }}
        run: rustup component add rustfmt

      - name: Install clippy
        if: ${{ steps.semrel.outputs.next-version != steps.semrel.outputs.current-version }}
        run: rustup +nightly component add clippy

      - name: Style
        if: ${{ steps.semrel.outputs.next-version != steps.semrel.outputs.current-version }}
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: -- --check

      - name: Lint
        if: ${{ steps.semrel.outputs.next-version != steps.semrel.outputs.current-version }}
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: clippy

      - name: Build
        if: ${{ steps.semrel.outputs.next-version != steps.semrel.outputs.current-version }}
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        if: ${{ steps.semrel.outputs.next-version != steps.semrel.outputs.current-version }}
        uses: actions-rs/cargo@v1
        with:
          command: test
