name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-semrel:
    uses: brianbruggeman/semrel/.github/workflows/setup-and-run-semrel.yml@main
    with:
      branch: 'main'

  cargo_fmt:
    needs: [run-semrel]
    if: ${{ needs.run-semrel.outputs.next-version != needs.run-semrel.outputs.current-version }}
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install cargo fmt
        run: rustup component add rustfmt
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: -- --check

  cargo_clippy:
    needs: [run-semrel]
    if: ${{ needs.run-semrel.outputs.next-version != needs.run-semrel.outputs.current-version }}
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install clippy
        run: rustup +nightly component add clippy
      - name: Cache cargo clippy
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-clippy-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: clippy

  cargo_build:
    needs: [run-semrel]
    if: ${{ needs.run-semrel.outputs.next-version != needs.run-semrel.outputs.current-version }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

  cargo_test:
    needs: [run-semrel]
    if: ${{ needs.run-semrel.outputs.next-version != needs.run-semrel.outputs.current-version }}
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
