name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo_fmt:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run semrel
        id: semrel
        uses: brianbruggeman/semrel@${{ github.ref }}

      - name: Install rust toolchain
        if: ${{ steps.semrel.outputs.version-changed == 'true' }}
        uses: dtolnay/rust-toolchain@stable

      - name: Install nightly with rustfmt and clippy
        if: ${{ steps.semrel.outputs.version-changed == 'true' }}
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Style
        if: ${{ steps.semrel.outputs.version-changed == 'true' }}
        run: cargo +nightly fmt -- --check

      - name: Lint
        if: ${{ steps.semrel.outputs.version-changed == 'true' }}
        run: cargo +nightly clippy

      - name: Build
        if: ${{ steps.semrel.outputs.version-changed == 'true' }}
        run: cargo build

      - name: Test
        if: ${{ steps.semrel.outputs.version-changed == 'true' }}
        run: cargo test
