name: Hello

on:
  push:

jobs:

  # detect-new-version:
  #   uses: ./.github/workflows/detect-new-version.yml
  #   secrets:
  #     token: ${{ secrets.GITHUB_TOKEN }}

  use-reusable-hello:
    uses: ./.github/workflows/world.yml

  use-output:
    needs: [use-reusable-hello]
    runs-on: ubuntu-latest

    steps:
      - name: Display Hello World
        run: echo "${{ job.reusable-hello.outputs.hello-output }}"